version: '3'
services: 
  mysql: 
    build: ./mysql
    volumes: 
     - /var/lib/mysql
    env_file: 
     - .env
  flask:
    build: ./flask
    links: 
     - mysql
    env_file: 
     - .env
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
     - flask
